# Site settings
title: Html-coder
email: vvbernacky@gmail.com
description: HTML coder / Front end developer. Freelance. HTML template creator. Best practices
baseurl: "/myblog" # the subpath of your site, e.g. /blog/
url: "http://http://vvbernacky.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
encoding: UTF-8 # кодировка

# Build settings
markdown: kramdown
pygments:         false
highlighter:      rouge